[build]
builder = "DOCKERFILE"
dockerfilePath = "/Dockerfile"
buildEnvironment = "V3"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig.us-west2]
numReplicas = 1
